---
#tasks for monitoring installation - Prometheus, Gafana, AlrtManager, Loki, Promtail
- name: add repository kube-prometheus-stack
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: add repo Loki-Stack
  command: helm repo add grafana https://grafana.github.io/helm-charts

- name: update repo
  command: helm repo update


- name: label monitoring node
  command: kubectl label node k3s-worker-node2 role=monitoring-node
  ignore_errors: true

- name: copy prometheus values
  copy:
    src: prometheus-values.yaml
    dest: /tmp/prometheus-values.yaml

- name: install kube-prometheus-stack
  command: >
    helm upgrade
    --install prometheus-stack prometheus-community/kube-prometheus-stack
    --namespace monitoring-stack
    --create-namespace
    --values /tmp/prometheus-values.yaml

- name: copy loki values
  copy:
    src: loki-values.yaml
    dest: /tmp/loki-values.yaml

- name: install Loki
  command: >
    helm upgrade
    --install loki grafana/loki
    --namespace monitoring-stack
    --values /tmp/loki-values.yaml
