---
#tasks for monitoring installation - Prometheus, Gafana, AlrtManager, Loki, Promtail
- name: add repository kube-prometheus-stack
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: add repo Loki-Stack
  command: helm repo add grafana https://grafana.github.io/helm-charts

- name: update repo
  command: helm repo update


- name: label monitoring node
  command: kubectl label node k3s-worker-node2 role=monitoring-node

- name: install kube-prometheus-stack
  command: helm upgrade
    --install prometheus-stack prometheus-community/kube-prometheus-stack
    --namespace monitoring-stack
    --create-namespace
    --set prometheus.nodeSelector."role"=monitoring-node
    --set grafana.nodeSelector."role"=monitoring-node
    --set grafana.service.type=NodePort
    --set grafana.service.nodePort=30300
    --set alertmanager.nodeSelector."role"=monitoring-node
    --set kube-state-metrics.nodeSelector."role"=monitoring-node
    --set prometheus-operator.nodeSelector."role"=monitoring-node

- name: install Loki
  command: helm upgrade
    --install loki grafana/loki-stack
    --namespace monitoring-stack
    --set loki.nodeSelector."role"=monitoring-node
    --set loki.isDefault=false
