---
#tasks for chaos mesh installation
- name: add chaos-mesh repo
  command: helm repo add chaos-mesh https://charts.chaos-mesh.org

- name: update repo
  command: helm repo update

- name: install chaos-mesh
  command: helm upgrade
    --install chaos-mesh chaos-mesh/chaos-mesh
    --namespace=chaos-mesh
    --create-namespace
    --set chaosDaemon.runtime=containerd
    --set chaosDaemon.socketPath=/run/k3s/containerd/containerd.sock
    --set dashboard.service.type=NodePort
    --set dashboard.service.nodePort=30400
    --set dashboard.nodeSelector."role"=monitoring-node
    --set controllerManager.nodeSelector."role"=monitoring-node
    --set controllerManager.webhookPort=9443
    --set dnsServer.nodeSelector."role"=monitoring-node
    --version 2.8.2

- name: wait for controller-manager
  command: kubectl rollout status deployment/chaos-controller-manager -n chaos-mesh

- name: label namespace for chaos
  command: kubectl label namespace app-production chaos-mesh.org/inject=enabled --overwrite

- name: label namepsace if empty
  command: kubectl label namespace app-production name=app-production --overwrite

- name: check pod
  command: kubectl get pods -n chaos-mesh
  register: chaosMeshPodStatus
  until: "'Running' in chaosMeshPodStatus.stdout"
  retries: 10
  delay: 10

- name: patch chaos-mesh service to expose port 10250
  command: kubectl patch svc chaos-mesh-controller-manager -n chaos-mesh --type='json' -p='[{"op":"add","path":"/spec/ports/-","value":{"name":"webhook-10250","port":10250,"protocol":"TCP","targetPort":10250}}]'
  ignore_errors: yes
