deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  useTestSchema: true
  auth_enabled: false
singleBinary:
  replicas: 1
  nodeSelector:
    role: monitoring-node
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
chunksCache:
  enabled: false
resultsCache:
  enabled: false
lokiCanary:
  enabled: false
gateway:
  enabled: false
test:
  enabled: false
