---
# tasks file for k3s_master
- name: install k3s
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip {{ master_private_ip }} --advertise-address {{ master_private_ip }}" sh -
  args:
    creates: /usr/local/bin/k3s

- name: wait for k3s service
  service:
    name: k3s
    state: started
  register: k3sStarted
  until: k3sStarted.status.ActiveState == "active"
  retries: 10
  delay: 10

- name: get master node status
  command: kubectl get node {{ inventory_hostname }}
  register: masterNodeStatus
  until: "'Ready' in masterNodeStatus.stdout"
  retries: 10
  delay: 10

- name: acquire k3s token
  command: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token

- name: copy kubeconfig to standard location
  shell: mkdir -p ~/.kube && cp /etc/rancher/k3s/k3s.yaml ~/.kube/config

- name: Download helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Install helm
  shell: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm
