[master]
k3s-master ansible_host=178.104.91.46 ansible_user=root ansible_ssh_private_key_file=~/.ssh/chaos-k3s-ssh-key

[workers]
k3s-worker-1 ansible_host=178.104.94.227 ansible_user=root ansible_ssh_private_key_file=~/.ssh/chaos-k3s-ssh-key
k3s-worker-2 ansible_host=178.104.37.43 ansible_user=root ansible_ssh_private_key_file=~/.ssh/chaos-k3s-ssh-key

[k3s_cluster:children]
master
workers
