[master]
k3s-master-node ansible_host=5.75.155.82 ansible_user=root ansible_ssh_private_key_file=~/.ssh/chaos-k3s-ssh-key master_private_ip=10.0.1.1

[workers]
k3s-worker-node1 ansible_host=5.75.158.248 ansible_user=root ansible_ssh_private_key_file=~/.ssh/chaos-k3s-ssh-key worker_private_ip=10.0.1.2
k3s-worker-node2 ansible_host=5.75.134.174 ansible_user=root ansible_ssh_private_key_file=~/.ssh/chaos-k3s-ssh-key worker_private_ip=10.0.1.3

[k3s_cluster:children]
master
workers
