[master]
k3s-master-node ansible_host=157.90.125.49 ansible_user=root ansible_ssh_private_key_file=~/.ssh/chaos-k3s-ssh-key master_private_ip=10.0.1.1

[workers]
k3s-worker-node1 ansible_host=157.90.125.87 ansible_user=root ansible_ssh_private_key_file=~/.ssh/chaos-k3s-ssh-key worker_private_ip=10.0.1.2 node_label=app
k3s-worker-node2 ansible_host=157.90.127.142 ansible_user=root ansible_ssh_private_key_file=~/.ssh/chaos-k3s-ssh-key worker_private_ip=10.0.1.3 node_label=monitoring

[k3s_cluster:children]
master
workers
