name: "Run Experiment"

on: 
  workflow_dispatch:
    inputs:
      experiment_type:
        options:
          - pod_kill
          - cpu_stress
          - memory_stress
          - network_delay
        type: choice
        description: Experiment to choose
        required: true  

jobs:
  Experiment:
    name: "Run Experiment"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get master IP
        run: |
          MASTER_IP=$(awk '/\[master\]/{flag=1; next} /\[/{flag=0} flag && /ansible_host/ {print $2}' inventory.ini | cut -d= -f2)
          echo "MASTER_IP=$MASTER_IP" >> $GITHUB_ENV
          
      - name: Copy to Remote Server
        uses: pierrickdelrieu/scp-action@v0.1.0
        with:
          host: ${{ env.MASTER_IP }}
          ssh_port: 22
          ssh_username: root
          ssh_key: ${{ secrets.CHAOS_SSH_PRIVATE_KEY }}
          source_dir: ./Chaos_experiment/
          destination_dir: /tmp

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CHAOS_SSH_PRIVATE_KEY }}" > ~/.ssh/ssh_key
          chmod 600 ~/.ssh/ssh_key

      - name: Disable host key checking
        run: |
          echo "StrictHostKeyChecking=no" >> ~/.ssh/config

      - name: Execute experiment
        run: |
          OUTPUT=$(ssh -i ~/.ssh/ssh_key \
            root@${{ env.MASTER_IP }} \
            "/tmp/run-experiment.sh ${{ inputs.experiment_type }}")
          echo "OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Experiment result: ${{ inputs.experiment_type }}",
              body: `### Output:\n\n\`\`\`\n${process.env.OUTPUT}\n\`\`\``
            })


    
