name: "Terraform Destory"

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'confirm' to destory"
        required: true
        default: "Not confirmed"      

jobs:
  terraform:
    name: "Destroy Terraform Infra"
    if: ${{ github.event.inputs.confirm == 'confirm' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ./Terraform
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Terraform with version
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5
          cli_config_credentials_token: ${{ secrets.TERRAFORM_LOGIN_TOKEN }}
          
      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform destroy
        id: destory
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}       
        run: terraform destroy -auto-approve -input=false
        
      - name: Log confirmation
        run: echo "Destroy confirmed by ${{ github.actor }}"
