name: "Terraform Apply Infra"

on: [workflow_dispatch]

jobs:
  terraform:
    name: "Apply Terraform Infra"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ./Terraform

      
    steps:
      - name: Checkout
        uses: actions/checkout@v4     
      
      - name: Setup Terraform with version
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5
          cli_config_credentials_token: ${{ secrets.TERRAFORM_LOGIN_TOKEN }}
          
      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate
      
      - name: terraform apply
        id: apply
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
        run: terraform apply -auto-approve -input=false

      - name: terraform output
        id: output
        run: |
          terraform output
          terraform output -json > ./tf-output.json

      - name: terraform output view
        run: cat ./tf-output.json   

      - name: Install jq (if needed)
        run: sudo apt-get update && sudo apt-get install -y jq

 
      - name: parse output to Ansible inventory
        run: | 
          set -e
          (
            echo "[master]"
            jq -r '
              to_entries[]
              | select(.key | contains("master"))
              | "\(.key | sub("-ip$"; "")) ansible_host=\(.value.value)"
            ' tf-output.json
          
            echo ""
            echo "[workers]"
            jq -r '
              to_entries[]
              | select(.key | contains("worker"))
              | "\(.key | sub("-ip$"; "")) ansible_host=\(.value.value)"
            ' tf-output.json
          
            echo ""
            echo "[k3s_cluster:children]"
            echo "master"
            echo "workers"
          ) > inventory.ini
          

      - name: Show inventory
        run: cat inventory.ini

      - name: Upload Ansible inventory to artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ansible-inventory
          path: inventory.ini
